@echo off
set ANTHROPIC_API_KEY=YOUR_ANTHROPIC_API_KEY_HERE
set MODEL=claude-3-7-sonnet-20250219
set PERPLEXITY_MODEL=sonar-pro
set MAX_TOKENS=4000
set TEMPERATURE=0.2
set DEBUG=false
set LOG_LEVEL=info
set DEFAULT_SUBTASKS=5
set DEFAULT_PRIORITY=medium
set PROJECT_NAME=Spotify Playlist Link Extractor
set PERPLEXITY_API_KEY=YOUR_PERPLEXITY_API_KEY_HERE 